const DISPLAY_COMMISSION = 'DISPLAY_COMMISSION';
const SUBMIT_OPERATION = 'SUBMIT_OPERATION';
const DELETE_OPERATION = 'DELETE_OPERATION';
const GET_DATA = 'GET_DATA';
export {DISPLAY_COMMISSION,SUBMIT_OPERATION,DELETE_OPERATION,GET_DATA};